### ISSUE TITLE
issue opening

### ISSUE THREAD

**Issue by lo69420** [useragents/Proxyless-TikTok-Username-Checker#11]
yoo i installed pip install -r requirements.txt in the Command Prompt but when i open main.py it instantly closes right after. same thing for the Username_generator i type in how many strings and how many character i want and when i press enter it closes?

**Comment by useragents** [comment]
There is **no issue with the username generator script**. The file `username_generator.py` will save the strings to an output file (`usernames.txt` if not changed) then an `input()` function is called waiting for the user to press enter to close.

`main.py` should not close instantly. I assume you don't have the modules installed correctly. Type the following into Command Prompt:

- pip install requests

- pip install colorama

Don't have PIP installed? View [here](https://pip.pypa.io/en/stable/installation/) to learn how to install PIP.

**Comment by useragents** [comment]
If you have the modules installed correctly and the `main.py` script still instantly closes, I have edited the script slightly as a small issue may have been your problem. Download the new version [here](https://github.com/useragents/Proxyless-TikTok-Username-Checker/archive/refs/heads/main.zip).

**Comment by lo69420** [comment]
> If you have the modules installed correctly and the `main.py` script still instantly closes, I have edited the script slightly as a small issue may have been your problem. Download the new version [here](https://github.com/useragents/Proxyless-TikTok-Username-Checker/archive/refs/heads/main.zip).

it works tyy!
