### ISSUE TITLE
Check for banned users?

### ISSUE THREAD

**Issue by lkeld** [useragents/Proxyless-TikTok-Username-Checker#12]
It works great, but there should be an option to check for banned users as often I find myself checking users that are banned.

**Comment by Al3xlol** [comment]
Hello you can’t make it check banned usernames as tiktok updated there endpoints for username checks and it gives blank json response

**Comment by useragents** [comment]
I can look into it. 👍

**Comment by Al3xlol** [comment]
> I can look into it. 👍

Unless you have top tier paid end points it won’t work
