### ISSUE TITLE
Error "AttributeError: module 'ctypes' has no attribute 'windll'"

### ISSUE THREAD

**Issue by Kev2FreshYo** [useragents/Proxyless-TikTok-Username-Checker#16]
entire error:
sh: 1: cls: not found
Traceback (most recent call last):
  File "/home/kev/Proxyless-TikTok-Username-Checker/main.py", line 94, in <module>
    obj.main()
  File "/home/kev/Proxyless-TikTok-Username-Checker/main.py", line 73, in main
    ctypes.windll.kernel32.SetConsoleTitleW("TikTok Username Checker | Developed by @useragents on Github")
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by RealCreepi** [comment]
This script has no Linux support so you will have to comment those lines out

**Comment by useragents** [comment]
`ctypes.windll` is specifically only for Windows and you're using it on a non-Windows environment. Alternatively, you can remove any lines using `ctypes` as it is not needed for this script to function.
