### ISSUE TITLE
[bug] Usernames show as available but never are

### ISSUE THREAD

**Issue by RealFX-Code** [useragents/Proxyless-TikTok-Username-Checker#19]
So i have ran the username checker on 2k+ 4 and 3 letter names and all the usernames it says are available aren't.
All of the usernames came up as unavailable when i tried setting them to my username on tiktok.

may just be me being stupid, if so, explain please.

**Comment by KosmosGithub** [comment]
This Means u might be rate limited or the user is banned

**Comment by useragents** [comment]
@KosmosGithub The script does not rate limit as of now.

@RealFX-Code Already answered [here](https://github.com/useragents/Proxyless-TikTok-Username-Checker/issues/3#issuecomment-1093979686)
