### ISSUE TITLE
cant open main

### ISSUE THREAD

**Issue by rzrv** [useragents/Proxyless-TikTok-Username-Checker#2]
i have installed everything got the usernames but I can't run main to see availability

**Comment by 59n** [comment]
Hey,

What is the error that you are getting?

**Comment by useragents** [comment]
What happens when you run the `main.py` script? @rzrv

**Comment by Sh0dy** [comment]
> What happens when you run the `main.py` script? @rzrv

for me nothing happens I open it I see the cmd then it disappears/closes itself

**Comment by rzrv** [comment]
@useragents i just had to reinstall pip and used pip3 instead. all working good now.
