### ISSUE TITLE
Error while importing modules. Please install the modules in requirements.txt

### ISSUE THREAD

**Issue by crozyy** [useragents/Proxyless-TikTok-Username-Checker#22]
![image](https://user-images.githubusercontent.com/73306982/163825883-5ca537c8-8d4a-4477-84b4-e174edcece1f.png)

how can i fix this?

**Comment by crozyy** [comment]
i did the "pip install -r requirements.txt"

**Comment by maxwalks** [comment]
I have the exact same problem and couldn't find an answer anywhere.

**Comment by maxwalks** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/78441835/163866244-85c9dc7b-c1e6-494e-aef8-e97e86fa38ce.png)
This is a screenshot of what i have.

**Comment by useragents** [comment]
Type the following into Command Prompt, then run the `main.py` script:

`pip install colorama`
`pip install requests`

**Comment by maxwalks** [comment]
> Type the following into Command Prompt, then run the `main.py` script:
> 
> `pip install colorama` `pip install requests`

It says its already satisfied, ran it after and still didnt work. Is there another solution to this?
