### ISSUE TITLE
IDK what to do

### ISSUE THREAD

**Issue by 28rbt** [useragents/Proxyless-TikTok-Username-Checker#23]
![screen132](https://user-images.githubusercontent.com/88858624/163831312-592d0bb7-71c3-412f-b67f-676e2c9ad45a.png)

**Comment by useragents** [comment]
This is my fault, I mistyped an attribute. This has been fixed, download the new version [here](https://github.com/useragents/Proxyless-TikTok-Username-Checker/archive/refs/heads/main.zip).
