### ISSUE TITLE
Error while importing modules. Please install the modules in requirements.txt

### ISSUE THREAD

**Issue by maxwalks** [useragents/Proxyless-TikTok-Username-Checker#25]
I cant find any fix to this.
Yes, i have done "pip install colorama" and "pip install requests".
![problem](https://user-images.githubusercontent.com/78441835/164510688-f82d3d8b-be25-430e-a88a-eb6dae470c60.png)

**Comment by useragents** [comment]
You likely have more than 1 Python version installed and when you installed the modules, they were installed to the wrong Python path.
