### ISSUE TITLE
usernames.txt not found

### ISSUE THREAD

**Issue by mrcoochieman** [useragents/Proxyless-TikTok-Username-Checker#29]
i made the file in different directories and in the same directory and still nothing this goes for everything else instagram username claimer etc

**Comment by useragents** [comment]
For whatever reason, Python is unable the locate the file. It must be put in the same directory and exact filename, if it still says that it's not found then Python can't find the file. This is not an issue with the script 👍

**Comment by mrcoochieman** [comment]
![Screenshot (291)](https://user-images.githubusercontent.com/104310842/164982877-bbee2ae8-d669-42fa-92ba-0010da981460.png)

still doesnt work
