### ISSUE TITLE
[Console] No usernames loaded in proxies.txt

### ISSUE THREAD

**Issue by ZyXousek** [useragents/Proxyless-TikTok-Username-Checker#35]
hi i have a problem. when i start run.bat, it shows big TIKTOK and this too: "[Console] No usernames loaded in proxies.txt"
what should i do?

**Comment by ArticsGorrila** [comment]
make a proxies.txt in directory and put usernames in there

**Comment by useragents** [comment]
This is a typo by me, it is supposed to say `No usernames loaded in usernames.txt`. I have fixed it in the latest version.
