### ISSUE TITLE
Does this work with PyDroid? 

### ISSUE THREAD

**Issue by CoolBoiYT** [useragents/Proxyless-TikTok-Username-Checker#4]
I've tried to run it on my phone using PyDroid. I did 'pip install - r requirements.txt'. It worked. Then I did 'python main.py' and got this error: 
![Screenshot_2022-04-09-16-19-33-514_ru iiec pydroid3](https://user-images.githubusercontent.com/61365543/162578189-9cf54976-de90-45a0-8847-084a72e78896.jpg)
Does anyone know how to fix it?

**Comment by useragents** [comment]
`ctypes.windll` is specifically only for Windows and you're using it on a non-Windows environment. Alternatively, you can remove any lines using `ctypes` as it is not needed for this script to function.
