### ISSUE TITLE
@lol-jude

### ISSUE THREAD

**Issue by VillainsRule4000** [useragents/Proxyless-TikTok-Username-Checker#43]
I believe that a user by the name of @lol-jude has copied your work.
https://github.com/lol-jude/Tiktok-Username-Checker

Is this true?

**Comment by useragents** [comment]
Yes, that is my work. You can even see the comment [here](https://github.com/glixxzzy/Tiktok-Username-Checker/commit/af3a0efd453f367c77156577b801a92dff15f773) that this user uploaded my files and edited them.

**Comment by VillainsRule4000** [comment]
I feel like you should report him, he's now impersonating Glixzzy, the original hacker of the game Blooket.
