### ISSUE TITLE
i can only see 16 names after that it just closed had to paste the script in python then run it from there for it to work also needed to add press enter to exit for no instant close

### ISSUE THREAD

**Issue by thijn20081** [useragents/Proxyless-TikTok-Username-Checker#6]

**Comment by useragents** [comment]
I don't understand exactly what you mean by this issue you are facing. The script will close after all usernames have been checked

**Comment by useragents** [comment]
The new version will now save available usernames to `Available.txt` and will wait for user input instead of instantly closing. Download the latest version [here](https://github.com/useragents/Proxyless-TikTok-Username-Checker/archive/refs/heads/main.zip).
